apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: s3-prober
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: metrics
      scrapeTimeout: 59s
    - interval: 60s
      path: /probe
      port: metrics
      scrapeTimeout: 59s
  selector:
    matchLabels:
      app: s3-prober
